apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ovia-devops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/paycenonoli/ovia-DevOps.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
