apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ovia-deploy
  name: ovia-deploy
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovia-deploy
  template:
    metadata:
      labels:
        app: ovia-deploy
    spec:
      containers:
        - image: ojpascale/devops-python:a454c0d271c3da900bc9867d01fee94d16d86082
          name: devops-python
