apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ovia-deploy
  name: ovia-deploy
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovia-deploy
  template:
    metadata:
      labels:
        app: ovia-deploy
    spec:
      containers:
        - image: ojpascale/devops-python:d6db3d9cf1c19ca3a77455ef13c028d6d5d3b93b
          name: devops-python
