apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ovia-deploy
  name: ovia-deploy
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovia-deploy
  template:
    metadata:
      labels:
        app: ovia-deploy
    spec:
      containers:
        - image: ojpascale/devops-python:b07441fbe804caeb1a627e82a82107c4b007639f
          name: devops-python
